nst_team_mapping = {
    "Minnesota Wild": "MIN",
    "Vegas Golden Knights": "VGK",
    "Ottawa Senators": "OTT",
    "Carolina Hurricanes": "CAR",
    "Columbus Blue Jackets": "CBJ",
    "Florida Panthers": "FLA",
    "Los Angeles Kings": "LAK",
    "New Jersey Devils": "NJD",
    "Montreal Canadiens": "MTL",
    "Colorado Avalanche": "COL",
    "Washington Capitals": "WSH",
    "Detroit Red Wings": "DET",
    "Tampa Bay Lightning": "TBL",
    "Vancouver Canucks": "VAN",
    "Dallas Stars": "DAL",
    "New York Rangers": "NYR",
    "Buffalo Sabres": "BUF",
    "Philadelphia Flyers": "PHI",
    "Edmonton Oilers": "EDM",
    "St Louis Blues": "STL",
    "Seattle Kraken": "SEA",
    "Toronto Maple Leafs": "TOR",
    "San Jose Sharks": "SJS",
    "Pittsburgh Penguins": "PIT",
    "Winnipeg Jets": "WPG",
    "Calgary Flames": "CGY",
    "Boston Bruins": "BOS",
    "Nashville Predators": "NSH",
    "Anaheim Ducks": "ANA",
    "Chicago Blackhawks": "CHI",
    "Arizona Coyotes": "ARI",
    "New York Islanders": "NYI",
    "Utah Mammoth": "UTA",
    "Utah Hockey Team": "UTA"
}

eh_team_mapping = {
    'S.J': 'SJS',
    'T.B': 'TBL',
    'N.J': 'NJD',
    'L.A': 'LAK'
}

team_full_names = {
    'MIN': 'Minnesota Wild',
    'VGK': 'Vegas Golden Knights',
    'OTT': 'Ottawa Senators',
    'CAR': 'Carolina Hurricanes',
    'CBJ': 'Columbus Blue Jackets',
    'FLA': 'Florida Panthers',
    'LA': 'Los Angeles Kings',
    'LAK': 'Los Angeles Kings',
    'NJ': 'New Jersey Devils',
    'NJD': 'New Jersey Devils',
    'MTL': 'Montreal Canadiens',
    'COL': 'Colorado Avalanche',
    'WSH': 'Washington Capitals',
    'DET': 'Detroit Red Wings',
    'TBL': 'Tampa Bay Lightning',
    'TB': 'Tampa Bay Lightning',
    'VAN': 'Vancouver Canucks',
    'DAL': 'Dallas Stars',
    'NYR': 'New York Rangers',
    'BUF': 'Buffalo Sabres',
    'PHI': 'Philadelphia Flyers',
    'EDM': 'Edmonton Oilers',
    'STL': 'St Louis Blues',
    'SEA': 'Seattle Kraken',
    'TOR': 'Toronto Maple Leafs',
    'SJ': 'San Jose Sharks',
    'SJS': 'San Jose Sharks',
    'PIT': 'Pittsburgh Penguins',
    'WPG': 'Winnipeg Jets',
    'CGY': 'Calgary Flames',
    'BOS': 'Boston Bruins',
    'NSH': 'Nashville Predators',
    'ANA': 'Anaheim Ducks',
    'CHI': 'Chicago Blackhawks',
    'ARI': 'Arizona Coyotes',
    'NYI': 'New York Islanders',
    'UTA': 'Utah Mammoth'
}

mlb_team_full_names = {
	"ARI": "Arizona Diamondbacks",
	"ATH": "Homeless Athletics",
	"ATL": "Atlanta Braves",
	"BAL": "Baltimore Orioles",
	"BOS": "Boston Red Sox",
	"CHC": "Chicago Cubs",
	"CHW": "Chicago White Sox",
	"CIN": "Cincinnati Reds",
	"CLE": "Cleveland Guardians",
	"COL": "Colorado Rockies",
	"DET": "Detroit Tigers",
	"HOU": "Houston Astros",
	"KCR": "Kansas City Royals",
	"LAA": "Los Angeles Angels",
	"LAD": "Los Angeles Dodgers",
	"MIA": "Miami Marlins",
	"MIL": "Milwaukee Brewers",
	"MIN": "Minnesota Twins",
	"NYM": "New York Mets",
	"NYY": "New York Yankees",
	"PHI": "Philadelia Phillies",
	"PIT": "Pittsburgh Pirates",
	"SDP": "San Diego Padres",
	"SEA": "Seattle Mariners",
	"SFG": "San Francisco Giants",
	"STL": "St. Louis Cardinals",
	"TBR": "Tampa Bay Rays",
	"TEX": "Texas Rangers",
	"TOR": "Toronto Blue Jays",
	"WSN": "Washington Nationals",
}
