name: Build and Push MLB Fantasy Reporter Docker Image
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    ###
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      #
      - name: Decrypt oauth key
        env:
          SECRET_PASSPHRASE: ${{ secrets.YAHOO_OAUTH_DECRYPT_KEY }}
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$SECRET_PASSPHRASE" \
          --output ./oauth.json oauth.json.gpg;
          ls
      #
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      #
      - name: Setup Buildx for Docker
        uses: docker/setup-buildx-action@v3
      #
      - name: Docker Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ${{ github.workspace }}
          tags: sohraub/mlb-fantasy-reporter:main
          cache-from: type=gha
          cache-to: type=gha,mode=max
    ###
