name: Scrape and Plot Skater Points
on:
  workflow_call:
    outputs:
      plot_artifact_name: 
        value: ${{ jobs.plot-graphs.outputs.plot_artifact_name }}
        description: Name of plot artifact

  workflow_dispatch:
    
env: 
  PLOTS_ARTIFACT_NAME: 'fantasy-fa-plot'

jobs:
  plot-graphs:
    runs-on: ubuntu-latest
    outputs:
      plot_artifact_name: ${{ steps.set-output.outputs.plot_artifact_name }}
    ###
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: hockey-stats/chart-plotting
      #
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      # 
      - name: Install Requirements
        run: pip install -r requirements.txt
      #
      - name: Choose position
        id: choose_pos
        shell: python
        run: |
          import os
          from datetime import datetime
          today = int(datetime.now().weekday())
          position = ['1B', '2B', '3B', 'C', 'OF', 'P', 'SP', 'RP'][today % 8]
          with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
              print(f"position={position}", file=fh)
      #
      - name: Process Data
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: python processing/for_fantasy_baseball/get_free_agent_summary.py -p ${{ steps.choose_pos.outputs.position }}
      #
      - name: Generate Charts
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: python3 plotting/fantasy/mlb_free_agents.py -p ${{ steps.choose_pos.outputs.position }}
      #
      - name: Save Charts as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PLOTS_ARTIFACT_NAME }}
          path: ./*png
          retention-days: 1
      #
      - name: Set Output for Artifact Name 
        id: set-output
        run: echo "plot_artifact_name=$PLOTS_ARTIFACT_NAME" >> "$GITHUB_OUTPUT"
    ###
