name: Scrape and Plot MLB Graphical Standings by Division
on:
  workflow_call:
    inputs:
      division:
        description: Integer corresponding to division for which to generate plot
        type: string
        default: '0'

    outputs:
      plot_artifact_name: 
        value: ${{ jobs.plot-graphs.outputs.plot_artifact_name }}
        description: Name of plot artifact

  workflow_dispatch:
    inputs:
      division:
        description: Integer corresponding to division for which to generate plot
        type: string
        default: '0'
    
env: 
  PLOTS_ARTIFACT_NAME: 'graphical_standings_plot'

jobs:
  plot-graphs:
    runs-on: ubuntu-latest
    container:
      image: sohraub/hockey-stats-web-scraper:main
    outputs:
      plot_artifact_name: ${{ steps.set-output.outputs.plot_artifact_name }}
    ###
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: hockey-stats/chart-plotting
      #
      - name: Generate Charts
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: python3 plotting/baseball/team_plots/plot_team_standings.py --division "${{ inputs.division }}"
      #
      - name: Save Charts as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PLOTS_ARTIFACT_NAME }}
          path: ./*png
          retention-days: 1
      #
      - name: Set Output for Artifact Name 
        id: set-output
        run: echo "plot_artifact_name=$PLOTS_ARTIFACT_NAME" >> "$GITHUB_OUTPUT"
    ###
