name: Scrape and Plot Game Report
on:
  workflow_call:
    inputs:
      last_game_id:
        description: The last game reported on.
        type: string
    outputs:
      plot_artifact_name:
        value: ${{ jobs.plot-graphs.outputs.plot_artifact_name }}
      game_id:
        value: ${{ jobs.scrape-data.outputs.game_id }}

env: 
  DATA_ARTIFACT_NAME: 'game-data'
  PLOTS_ARTIFACT_NAME: 'game-plot'

jobs:
  scrape-data:

    runs-on: ubuntu-latest

    container:
      image: sohraub/hockey-stats-web-scraper:main

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      actions: write
      contents: read
      
    steps: 
      - name: Check if any new games are available
        id: check
        env:
          LAST_GAME: ${{ inputs.last_game_id }}
        run: |
          cd /home/scraping
          python3 check_for_new_games.py -y 2024 -g $LAST_GAME

      - name: Scrape game data
        if: steps.check.outputs.game_id != 'NONE'
        run: |
          cd /home/scraping
          python3 scrape_game_data.py -y 2024 -g ${{ steps.check.outputs.game_id }}

      - name: Save raw game data as artifact
        if: steps.check.outputs.game_id != 'NONE'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.DATA_ARTIFACT_NAME }}
          path: /home/scraping/tables/*csv
          retention-days: 1

      - name: Set output for artifact name
        if: steps.check.outputs.game_id != 'NONE'
        id: set-output
        run: echo "data_artifact_name=$DATA_ARTIFACT_NAME" >> "$GITHUB_OUTPUT"

    outputs:
      game_id: ${{ steps.check.outputs.game_id }}
#############
#############
  plot-graphs:

    runs-on: ubuntu-latest
    needs: scrape-data

    env: 
      GAME_ID: ${{ needs.scrape-data.outputs.game_id }}

    steps:
      - name: Checkout
        if: needs.scape-data.outputs.game_id != 'NONE'
        uses: actions/checkout@v4
        with:
          repository: hockey-stats/chart-plotting

      - name: Download data artifact
        if: needs.scape-data.outputs.game_id != 'NONE'
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.DATA_ARTIFACT_NAME }}
          
      - name: Check file structure
        if: needs.scape-data.outputs.game_id != 'NONE'
        run: |
          ls -lrt;

      - name: Setup Python
        if: needs.scape-data.outputs.game_id != 'NONE'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install requirements
        if: needs.scape-data.outputs.game_id != 'NONE'
        run: pip install -r requirements.txt

      - name: Process raw data
        if: needs.scape-data.outputs.game_id != 'NONE'
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python3 processing/for_game_report/process_game_tables.py -p ./ -g $GAME_ID

      - name: Generate chart
        if: needs.scape-data.outputs.game_id != 'NONE'
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python3 plotting/game_report/assemble_report.py -g $GAME_ID

      - name: Save chart as artifact
        if: needs.scape-data.outputs.game_id != 'NONE'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PLOTS_ARTIFACT_NAME }}
          path: ./*png
          retention-days: 1

      - name: Set output for artifact name
        if: needs.scape-data.outputs.game_id != 'NONE'
        id: set-output
        run: echo "plot_artifact_name=$PLOTS_ARTIFACT_NAME" >> "$GITHUB_OUTPUT"
